from typing import Protocol
from lifesync.shared_kernel.domain.value_objects import ChatId
from lifesync.projects.domain.entities import Project

class ProjectRepository(Protocol):
    async def get_by_id(self, project_id: int) -> Project | None: ...
    async def list_by_chat(self, chat_id: ChatId) -> list[Project]: ...
    async def save(self, project: Project) -> Project: ...
    async def delete(self, project_id: int) -> None: ...
