from typing import Protocol
from datetime import date
from lifesync.shared_kernel.domain.value_objects import ChatId
from lifesync.habits.domain.entities import Habit, HabitCheckIn

class HabitRepository(Protocol):
    async def get_by_id(self, habit_id: int) -> Habit | None: ...
    async def list_by_chat(self, chat_id: ChatId) -> list[Habit]: ...
    async def save(self, habit: Habit) -> Habit: ...
    
class HabitCheckInRepository(Protocol):
    async def get_by_habit_and_date(self, habit_id: int, effective_date: date) -> HabitCheckIn | None: ...
    async def get_last_checkin(self, habit_id: int) -> HabitCheckIn | None: ...
    async def list_by_habit_in_range(self, habit_id: int, start: date, end: date) -> list[HabitCheckIn]: ...
    async def save(self, checkin: HabitCheckIn) -> HabitCheckIn: ...
