from datetime import date
from typing import Protocol

from lifesync.shared_kernel.domain.value_objects import ChatId
from lifesync.tasks.domain.entities import Task


class TaskRepository(Protocol):
    async def get_by_id(self, task_id: int) -> Task | None: ...
    async def list_by_project(self, project_id: int) -> list[Task]: ...
    async def list_unfinished_before(self, chat_id: ChatId, d: date) -> list[Task]: ...
    async def save(self, task: Task) -> Task: ...
    async def delete(self, task_id: int) -> None: ...
    async def delete_by_project_id(self, project_id: int) -> None: ...
